defaults:
  - _self_
  - task: ik_parquet_DeltaJoint

_target_: diffusion_policy.workspace.train_diffusion_resnet_lowdim_workspace.TrainDiffusionResNetLowdimWorkspace

# 单步IK训练，长horizon的作用有限，主要n_
horizon: 20         # ← 序列总长 4
n_obs_steps: 3      # ← 用3帧历史obs作为global_cond (3×20=60维)
n_action_steps: 4   #← 推理时只执行4步 1
pred_action_steps_only: true  # ← 训练时也只对这4步算loss

training:
  device: "cuda:0"
  seed: 42
  debug: false
  resume: false
  lr_scheduler: cosine
  lr_warmup_steps: 1000 # 需要根据数据集大小调整
  num_epochs: 200
  gradient_accumulate_every: 1
  tqdm_interval_sec: 1.0
  rollout_every: 100000000000
  checkpoint_every: 10
  val_every: 1
  sample_every: 5
  max_train_steps: null
  max_val_steps: null
  use_ema: true # 使用EMA模型

policy:
  _target_: diffusion_policy.policy.diffusion_resnet_lowdim_policy.DiffusionResNetLowdimPolicy
  horizon: ${horizon}
  obs_dim: 20
  action_dim: 6
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}

  obs_as_global_cond: true  # 必须为 true
  pred_action_steps_only: ${pred_action_steps_only}
  obs_as_local_cond: false
  oa_step_convention: false
  num_inference_steps: 10 # 设置推理步数为10步，默认跟随noise_scheduler.config.num_train_timesteps=100

  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small
    prediction_type: epsilon

  model:
    _target_: diffusion_policy.model.diffusion.conditional_resnet1d.ConditionalResNet1D
    input_dim: 6
    global_cond_dim: ${eval:'${n_obs_steps} * 20'}
    hidden_dim: 256    # 对应你代码里的 hidden_dim
    n_blocks: 6       # 对应你代码里的 n_blocks

  #obs_encoder_hidden_dims: [256, 256]
  #obs_encoder_output_dim: 256

dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: true
  pin_memory: true
  persistent_workers: false

val_dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: false
  pin_memory: true
  persistent_workers: false

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.9, 0.999]
  weight_decay: 1.0e-4

logging:
  project: diffusion_policy_ik
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_ik_unet_lowdim_${task.name}
  tags: ["ik_resnet_lowdim", "${task.name}"]
  id: null
  group: null
  resume: false

checkpoint:
  topk:
    monitor_key: val_loss
    mode: min
    k: 5
    format_str: 'resnet_DeltaJoint_h${horizon}_obs${n_obs_steps}_act${n_action_steps}-epoch={epoch:04d}-val_loss={val_loss:.6f}.ckpt'
  save_last_ckpt: true
  save_last_snapshot: false

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel 
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999